### ISSUE TITLE
Why is the result different?

### ISSUE THREAD

**Issue by ZaiGal** [PCBSCalc/Issue-Tracker#1]
<img width="960" alt="png" src="https://user-images.githubusercontent.com/77733212/105178436-ed670e80-5b1f-11eb-82a6-01764acd58f7.png">
<img width="960" alt="png" src="https://user-images.githubusercontent.com/77733212/105178451-f48e1c80-5b1f-11eb-8202-75855335e58c.png">

**Comment by AhRoon** [comment]
Have you read this on our discord server?
Q. The calculator score and the in-game scores are different! Is it nornal?
A. Yes, try using XMP(Auto ram overclock) before you benchmark their computer.

Right, try using XMP on UEFI menu (Hold F3 before booting to desktop)

**Comment by AhRoon** [comment]
Is the above solution helped? I'm waiting for response! Inactive issue might be closed after 8 days, so please let me know.

**Comment by ZaiGal** [comment]
Hi. Yes. Helped so much. So sorry for the late reply. Was busy playing pc sim. 😁😆😆. Thanks for the advice. Help me through the game. 👍🏻👍🏻👍🏻👍🏻
--
Sent from myMail for Android Tuesday, 26 January 2021, 10:43pm +00:00 from Ah_Roon  notifications@github.com :

**Comment by AhRoon** [comment]
Closed #1.
