### ISSUE TITLE
Build Maker

### ISSUE THREAD

**Issue by Crentzu** [PCBSCalc/Issue-Tracker#2]
When I use Build Maker the site frozen
Windows 10, Brave Browser Latest Version

**Comment by AhRoon** [comment]
Strange, can you tell me about your PC Spec? If your PC Spec is bad it might not be possible to handle the calculation.

**Comment by AhRoon** [comment]
Are you there? According to Code on Conduct, inactive issue may be closed after 14 days and I'm waiting for your response. If you're there, can you tell me the PC Spec? Otherwise, I cannot help you resolving this issue.

**Comment by AhRoon** [comment]
Issue closed due to author's inactivity.
